In [80]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from sklearn.preprocessing import OrdinalEncoder
from numpy import asarray

from sklearn.tree          import DecisionTreeClassifier
from sklearn.ensemble      import RandomForestClassifier
from sklearn.ensemble      import ExtraTreesClassifier

import time
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
np.random.seed(0)

In [81]:
df5 = pd.read_csv('five_sec')
df5.head()

,dataset_5secondWindow.csv,id,time,activityrecognition#0,activityrecognition#1,android.sensor.accelerometer#mean,android.sensor.accelerometer#min,android.sensor.accelerometer#max,android.sensor.accelerometer#std,android.sensor.game_rotation_vector#mean,...,sound#mean,sound#min,sound#max,sound#std,speed#mean,speed#min,speed#max,speed#std,target,user
0,0.0,16170.0,78.0,NaN,100.0,9.811476,9.758895,9.849411,0.014626,0.029340,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,Still,U12
1,1.0,15871.0,145.0,NaN,100.0,9.939207,7.707437,17.146631,1.775944,0.999925,...,89.200210,89.065143,89.335277,0.191013,16.539349,16.539349,16.539349,0.628595,Car,U12
2,2.0,16811.0,150.0,NaN,100.0,9.827178,9.804817,9.849262,0.011199,0.665215,...,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,Still,U12
3,3.0,15831.0,105.0,NaN,77.0,9.673039,7.659674,12.304298,0.862553,0.996221,...,87.470377,87.470377,87.470377,2.284186,17.739895,17.739895,17.739895,0.628595,Car,U12
4,4.0,876.0,77.0,NaN,100.0,9.993466,8.965621,10.891645,0.504117,0.563792,...,89.770732,89.770732,89.770732,0.006389,9.000000,9.000000,9.000000,NaN,Car,U1

In [82]:
oe = OrdinalEncoder()
cd = asarray(df5['user'])
df5['user'] = oe.fit_transform(cd.reshape(-1,1))
print(df5['user'].value_counts())

0.0     2470
3.0      820
1.0      531
10.0     397
6.0      331
9.0      279
5.0      271
7.0      227
11.0     214
2.0      167
4.0       90
12.0      79
8.0       17
Name: user, dtype: int64

In [83]:
df5 = df5.sort_values(by='user')
df5

,dataset_5secondWindow.csv,id,time,activityrecognition#0,activityrecognition#1,android.sensor.accelerometer#mean,android.sensor.accelerometer#min,android.sensor.accelerometer#max,android.sensor.accelerometer#std,android.sensor.game_rotation_vector#mean,...,sound#mean,sound#min,sound#max,sound#std,speed#mean,speed#min,speed#max,speed#std,target,user
2946,2946.0,5228.0,190.0,NaN,92.0,10.179832,10.137434,10.207683,0.020380,0.995086,...,84.350732,84.350732,84.350732,0.923820,NaN,NaN,NaN,NaN,Train,0.0
3075,3075.0,5835.0,193.0,NaN,35.0,10.179362,9.853068,10.587065,0.167584,0.987558,...,89.762268,89.762268,89.762268,0.001198,NaN,NaN,NaN,NaN,Train,0.0
3076,3076.0,2274.0,256.0,NaN,8.0,9.657759,9.029124,10.286443,0.414025,0.844973,...,89.769040,89.769040,89.769040,0.013131,30.75,30.75,30.75,NaN,Car,0.0
3077,3077.0,7287.0,86.0,NaN,100.0,10.299321,8.088142,12.456252,1.604990,0.968824,...,88.572737,88.572737,88.572737,0.095157,0.75,0.75,0.75,NaN,Walking,0.0
3079,3079.0,184.0,91.0,NaN,85.0,9.729062,7.139446,14.355289,2.184604,0.928255,...,89.773691,89.767912,89.779470,0.008173,11.00,11.00,11.00,NaN,Bus,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3307,3307.0,12836.0,94.0,NaN,85.0,10.926161,7.289184,16.733950,2.618939,NaN,...,83.545534,83.545534,83.545534,1.800958,NaN,NaN,NaN,NaN,Walking,12.0
4087,4087.0,12806.0,64.0,NaN,100.0,11.173896,6.759052,17.244942,2.834614,NaN,...,78.116997,78.116997,78.116997,1.800958,NaN,NaN,NaN,NaN,Walking,12.0
3576,3576.0,12897.0,56.0,NaN,100.0,8.883861,4.312250,14.790456,3.825252,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Walking,12.0
5552,5552.0,12725.0,138.0,NaN,8.0,10.535515,10.125175,10.749877,0.169090,NaN,...,70.021185,70.021185,70.021185,1.639766,NaN,NaN,NaN,NaN,Train,12.0
5893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
df5.reset_index(inplace=True)

In [85]:
df5.head()

,index,dataset_5secondWindow.csv,id,time,activityrecognition#0,activityrecognition#1,android.sensor.accelerometer#mean,android.sensor.accelerometer#min,android.sensor.accelerometer#max,android.sensor.accelerometer#std,...,sound#mean,sound#min,sound#max,sound#std,speed#mean,speed#min,speed#max,speed#std,target,user
0,2946,2946.0,5228.0,190.0,NaN,92.0,10.179832,10.137434,10.207683,0.020380,...,84.350732,84.350732,84.350732,0.923820,NaN,NaN,NaN,NaN,Train,0.0
1,3075,3075.0,5835.0,193.0,NaN,35.0,10.179362,9.853068,10.587065,0.167584,...,89.762268,89.762268,89.762268,0.001198,NaN,NaN,NaN,NaN,Train,0.0
2,3076,3076.0,2274.0,256.0,NaN,8.0,9.657759,9.029124,10.286443,0.414025,...,89.769040,89.769040,89.769040,0.013131,30.75,30.75,30.75,NaN,Car,0.0
3,3077,3077.0,7287.0,86.0,NaN,100.0,10.299321,8.088142,12.456252,1.604990,...,88.572737,88.572737,88.572737,0.095157,0.75,0.75,0.75,NaN,Walking,0.0
4,3079,3079.0,184.0,91.0,NaN,85.0,9.729062,7.139446,14.355289,2.184604,...,89.773691,89.767912,89.779470,0.008173,11.00,11.00,11.00,NaN,Bus,0.0

In [86]:
df5 = df5.drop(columns=['dataset_5secondWindow.csv', 'id', 'speed#std', 'index', 'activityrecognition#0'])

In [87]:
df5.isnull().sum().sort_values(ascending=False).head(30)

android.sensor.step_counter#std                   5662
android.sensor.proximity#std                      5611
android.sensor.proximity#max                      4775
android.sensor.proximity#min                      4775
android.sensor.proximity#mean                     4775
android.sensor.pressure#std                       4766
android.sensor.step_counter#max                   4407
android.sensor.step_counter#min                   4407
android.sensor.step_counter#mean                  4407
android.sensor.pressure#min                       3976
android.sensor.pressure#mean                      3976
android.sensor.pressure#max                       3976
android.sensor.light#std                          3770
speed#mean                                        2374
speed#min                                         2374
speed#max                                         2374
sound#std                                         1832
android.sensor.light#mean                         1513
android.sensor.light#max                          1513
android.sensor.light#min                          1513
sound#min                                          995
sound#mean                                         995
sound#max                                          995
android.sensor.magnetic_field_uncalibrated#std     807
android.sensor.game_rotation_vector#std            801
android.sensor.gyroscope_uncalibrated#std          800
android.sensor.game_rotation_vector#mean           800
android.sensor.game_rotation_vector#min            800
android.sensor.game_rotation_vector#max            800
android.sensor.magnetic_field_uncalibrated#max     800
dtype: int64

In [88]:
df5_num = df5.drop(['target'], axis=1)
df5_num.head()

,time,activityrecognition#1,android.sensor.accelerometer#mean,android.sensor.accelerometer#min,android.sensor.accelerometer#max,android.sensor.accelerometer#std,android.sensor.game_rotation_vector#mean,android.sensor.game_rotation_vector#min,android.sensor.game_rotation_vector#max,android.sensor.game_rotation_vector#std,...,android.sensor.step_counter#max,android.sensor.step_counter#std,sound#mean,sound#min,sound#max,sound#std,speed#mean,speed#min,speed#max,user
0,190.0,92.0,10.179832,10.137434,10.207683,0.020380,0.995086,0.995067,0.995112,0.000017,...,NaN,NaN,84.350732,84.350732,84.350732,0.923820,NaN,NaN,NaN,0.0
1,193.0,35.0,10.179362,9.853068,10.587065,0.167584,0.987558,0.987359,0.987745,0.000117,...,NaN,NaN,89.762268,89.762268,89.762268,0.001198,NaN,NaN,NaN,0.0
2,256.0,8.0,9.657759,9.029124,10.286443,0.414025,0.844973,0.840452,0.851091,0.004017,...,NaN,NaN,89.769040,89.769040,89.769040,0.013131,30.75,30.75,30.75,0.0
3,86.0,100.0,10.299321,8.088142,12.456252,1.604990,0.968824,0.956427,0.975352,0.008850,...,711.0,NaN,88.572737,88.572737,88.572737,0.095157,0.75,0.75,0.75,0.0
4,91.0,85.0,9.729062,7.139446,14.355289,2.184604,0.928255,0.925184,0.931989,0.002932,...,NaN,NaN,89.773691,89.767912,89.779470,0.008173,11.00,11.00,11.00,0.0

In [89]:
from sklearn.impute import KNNImputer, SimpleImputer

In [90]:
knn = KNNImputer(n_neighbors=2)
imputer = SimpleImputer(strategy='mean', missing_values=np.nan)

In [91]:
df5_num = imputer.fit_transform(df5_num)

In [92]:
df5_num = pd.DataFrame(df5_num)

In [93]:
df5_num.isnull().sum().sort_values(ascending=False)

0     0
49    0
35    0
36    0
37    0
     ..
27    0
28    0
29    0
30    0
65    0
Length: 66, dtype: int64

In [94]:
df5_num.head()

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,65
0,190.0,92.0,10.179832,10.137434,10.207683,0.020380,0.995086,0.995067,0.995112,0.000017,...,10112.769334,2.959475,84.350732,84.350732,84.350732,0.923820,8.235254,8.216747,8.253528,0.0
1,193.0,35.0,10.179362,9.853068,10.587065,0.167584,0.987558,0.987359,0.987745,0.000117,...,10112.769334,2.959475,89.762268,89.762268,89.762268,0.001198,8.235254,8.216747,8.253528,0.0
2,256.0,8.0,9.657759,9.029124,10.286443,0.414025,0.844973,0.840452,0.851091,0.004017,...,10112.769334,2.959475,89.769040,89.769040,89.769040,0.013131,30.750000,30.750000,30.750000,0.0
3,86.0,100.0,10.299321,8.088142,12.456252,1.604990,0.968824,0.956427,0.975352,0.008850,...,711.000000,2.959475,88.572737,88.572737,88.572737,0.095157,0.750000,0.750000,0.750000,0.0
4,91.0,85.0,9.729062,7.139446,14.355289,2.184604,0.928255,0.925184,0.931989,0.002932,...,10112.769334,2.959475,89.773691,89.767912,89.779470,0.008173,11.000000,11.000000,11.000000,0.0

In [95]:
df5_num.shape

(5894, 66)

In [96]:
df5 = pd.concat([df5_num, df5['target']], axis=1)
df5.head()

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,target
0,190.0,92.0,10.179832,10.137434,10.207683,0.020380,0.995086,0.995067,0.995112,0.000017,...,2.959475,84.350732,84.350732,84.350732,0.923820,8.235254,8.216747,8.253528,0.0,Train
1,193.0,35.0,10.179362,9.853068,10.587065,0.167584,0.987558,0.987359,0.987745,0.000117,...,2.959475,89.762268,89.762268,89.762268,0.001198,8.235254,8.216747,8.253528,0.0,Train
2,256.0,8.0,9.657759,9.029124,10.286443,0.414025,0.844973,0.840452,0.851091,0.004017,...,2.959475,89.769040,89.769040,89.769040,0.013131,30.750000,30.750000,30.750000,0.0,Car
3,86.0,100.0,10.299321,8.088142,12.456252,1.604990,0.968824,0.956427,0.975352,0.008850,...,2.959475,88.572737,88.572737,88.572737,0.095157,0.750000,0.750000,0.750000,0.0,Walking
4,91.0,85.0,9.729062,7.139446,14.355289,2.184604,0.928255,0.925184,0.931989,0.002932,...,2.959475,89.773691,89.767912,89.779470,0.008173,11.000000,11.000000,11.000000,0.0,Bus

In [97]:
oe = OrdinalEncoder()
cd = asarray(df5['target'])
df5['target'] = oe.fit_transform(cd.reshape(-1,1))
print(df5['target'].value_counts())

1.0    1180
3.0    1179
2.0    1179
0.0    1178
4.0    1177
Name: target, dtype: int64

In [98]:
df5.head()

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,65,target
0,190.0,92.0,10.179832,10.137434,10.207683,0.020380,0.995086,0.995067,0.995112,0.000017,...,2.959475,84.350732,84.350732,84.350732,0.923820,8.235254,8.216747,8.253528,0.0,3.0
1,193.0,35.0,10.179362,9.853068,10.587065,0.167584,0.987558,0.987359,0.987745,0.000117,...,2.959475,89.762268,89.762268,89.762268,0.001198,8.235254,8.216747,8.253528,0.0,3.0
2,256.0,8.0,9.657759,9.029124,10.286443,0.414025,0.844973,0.840452,0.851091,0.004017,...,2.959475,89.769040,89.769040,89.769040,0.013131,30.750000,30.750000,30.750000,0.0,1.0
3,86.0,100.0,10.299321,8.088142,12.456252,1.604990,0.968824,0.956427,0.975352,0.008850,...,2.959475,88.572737,88.572737,88.572737,0.095157,0.750000,0.750000,0.750000,0.0,4.0
4,91.0,85.0,9.729062,7.139446,14.355289,2.184604,0.928255,0.925184,0.931989,0.002932,...,2.959475,89.773691,89.767912,89.779470,0.008173,11.000000,11.000000,11.000000,0.0,0.0

In [99]:
df5 = df5.rename(columns={65: 'user'})

In [100]:
df5 = df5.drop([5893, 1], axis=0)
df5

,0,1,2,3,4,5,6,7,8,9,...,57,58,59,60,61,62,63,64,user,target
0,190.0,92.0,10.179832,10.137434,10.207683,0.020380,0.995086,0.995067,0.995112,0.000017,...,2.959475,84.350732,84.350732,84.350732,0.923820,8.235254,8.216747,8.253528,0.0,3.0
2,256.0,8.0,9.657759,9.029124,10.286443,0.414025,0.844973,0.840452,0.851091,0.004017,...,2.959475,89.769040,89.769040,89.769040,0.013131,30.750000,30.750000,30.750000,0.0,1.0
3,86.0,100.0,10.299321,8.088142,12.456252,1.604990,0.968824,0.956427,0.975352,0.008850,...,2.959475,88.572737,88.572737,88.572737,0.095157,0.750000,0.750000,0.750000,0.0,4.0
4,91.0,85.0,9.729062,7.139446,14.355289,2.184604,0.928255,0.925184,0.931989,0.002932,...,2.959475,89.773691,89.767912,89.779470,0.008173,11.000000,11.000000,11.000000,0.0,0.0
5,103.0,100.0,10.000198,9.990616,10.020722,0.010132,0.963362,0.963298,0.963423,0.000047,...,2.959475,83.561689,83.561689,83.561689,6.790333,8.235254,8.216747,8.253528,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5888,47.0,100.0,10.672879,6.701437,14.237094,2.590851,0.759280,0.743872,0.771629,0.011876,...,2.959475,78.724855,78.451658,78.997213,1.913065,8.235254,8.216747,8.253528,12.0,4.0
5889,94.0,85.0,10.926161,7.289184,16.733950,2.618939,0.759280,0.743872,0.771629,0.011876,...,2.959475,83.545534,83.545534,83.545534,1.800958,8.235254,8.216747,8.253528,12.0,4.0
5890,64.0,100.0,11.173896,6.759052,17.244942,2.834614,0.759280,0.743872,0.771629,0.011876,...,2.959475,78.116997,78.116997,78.116997,1.800958,8.235254,8.216747,8.253528,12.0,4.0
5891,56.0,100.0,8.883861,4.312250,14.790456,3.825252,0.759280,0.743872,0.771629,0.011876,...,2.959475,78.724855,78.451658,78.997213,1.913065,8.235254,8.216747,8.253528,12.0,4.0
5892,138.0,8.0,10.535515,10.125175,10.749877,0.169090,0.759280,0.743872,0.771629,0.011876,...,2.959475,70.021185,70.021185,70.021185,1.639766,8.235254,8.216747,8.253528,12.0,3.0

In [101]:
df5.user.value_counts()

0.0     2469
3.0      820
1.0      531
10.0     397
6.0      331
9.0      279
5.0      271
7.0      227
11.0     214
2.0      167
4.0       90
12.0      79
8.0       17
Name: user, dtype: int64

In [102]:

data_test = df5.iloc[:2469, :]
data_train = df5.iloc[2469: , :]

In [103]:
X_train = data_train.iloc[:,:66]
y_train = data_train.iloc[:, 66:]

X_test = data_test.iloc[:, :66]
y_test = data_test.iloc[:, 66:]

In [104]:
tree_classifiers= {
  "Decision Tree": DecisionTreeClassifier(),
  "Extra Trees":ExtraTreesClassifier(),
  "Random Forest": RandomForestClassifier()
}

In [105]:
results = pd.DataFrame({'Model': [], 'Accuracy': [], 'Bal Acc.': [], 'Time': []})

for model_name, model in tree_classifiers.items():
    
    start_time = time.time()
    model.fit(X_train, y_train)
    total_time = time.time() - start_time
        
    pred = model.predict(X_test)
    
    results = results.append({"Model":    model_name,
                              "Accuracy": accuracy_score(y_test, pred)*100,
                              "Bal Acc.": balanced_accuracy_score(y_test, pred)*100,
                              "Time":     total_time},
                              ignore_index=True)
                              
                              
results_ord = results.sort_values(by=['Accuracy'], ascending=False, ignore_index=True)
results_ord.index += 1 
results_ord.style.bar(subset=['Accuracy', 'Bal Acc.'], vmin=0, vmax=100, color='Blues')

/Users/szokirov/opt/anaconda3/envs/strive/lib/python3.10/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/Users/szokirov/opt/anaconda3/envs/strive/lib/python3.10/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/var/folders/mc/zp9qp1010tx0w0zq76z35wh00000gn/T/ipykernel_22464/3920733270.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append({"Model":    model_name,
/Users/szokirov/opt/anaconda3/envs/strive/lib/python3.10/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/var/folders/mc/zp9qp1010tx0w0zq76z35wh00000gn/T/ipykernel_22464/3920733270.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)
/Users/szokirov/opt/anaconda3/envs/strive/lib/python3.10/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/var/folders/mc/zp9qp1010tx0w0zq76z35wh00000gn/T/ipykernel_22464/3920733270.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append({"Model":    model_name,
/Users/szokirov/opt/anaconda3/envs/strive/lib/python3.10/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/var/folders/mc/zp9qp1010tx0w0zq76z35wh00000gn/T/ipykernel_22464/3920733270.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)
/Users/szokirov/opt/anaconda3/envs/strive/lib/python3.10/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/var/folders/mc/zp9qp1010tx0w0zq76z35wh00000gn/T/ipykernel_22464/3920733270.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append({"Model":    model_name,

This is the results we get by imputing missing values with KNN Imputer

# Model	Accuracy	Bal Acc.	Time

1	Random Forest	41.109761	45.152660	1.048881

2	Extra Trees	35.965978	37.801168	0.270085

3	Decision Tree	33.576347	39.065017	0.145095

# Imputed values with Simple Imputer and mean strategy
# Model	Accuracy	Bal Acc.	Time

1	Random Forest	51.964358	57.399065	0.864444

2	Extra Trees	45.484002	49.556040	0.224357

3	Decision Tree	36.127987	40.386092	0.104342